name = "check_regexp"
description = "release and documentation checks for regexp"
version = "0.1.0-dev"

authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["tooling", "checks"]

executables = ["check_regexp"]

[[depends-on]]
gnat_native = "=15.2.1"

[[depends-on]]
regexp = "*"

[[depends-on]]
project_tools = "*"
